#!/usr/bin/env node
// Generates src/app/themes.css from the theme definitions below.
// Run with `node scripts/generate-themes.mjs` after changing a theme's hue/sat/radius.
// Keeping this as a generator (instead of hand-written CSS) avoids 20 blocks of
// hand-typed HSL triples getting out of sync or containing typos.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Themes with a bright/yellow-family primary read poorly with white text on
// the primary color, so they get dark text on primary instead.
const DARK_TEXT_ON_PRIMARY = new Set(["sunset", "gold", "cyberpunk"]);

export const THEMES = [
  { key: "default", label: "Default", hue: 217, sat: 91, radius: 0.75 },
  { key: "midnight", label: "Midnight", hue: 243, sat: 75, radius: 0.6 },
  { key: "ocean", label: "Ocean", hue: 189, sat: 90, radius: 0.9 },
  { key: "forest", label: "Forest", hue: 142, sat: 65, radius: 0.6 },
  { key: "sunset", label: "Sunset", hue: 24, sat: 92, radius: 0.75 },
  { key: "royal", label: "Royal", hue: 271, sat: 75, radius: 0.6 },
  { key: "crimson", label: "Crimson", hue: 347, sat: 75, radius: 0.5 },
  { key: "gold", label: "Gold Rush", hue: 40, sat: 92, radius: 0.5 },
  { key: "cyberpunk", label: "Cyberpunk", hue: 320, sat: 85, radius: 0.15 },
  { key: "mono", label: "Slate Mono", hue: 220, sat: 8, radius: 0.25 },
];

function clamp(n, min, max) {
  return Math.min(max, Math.max(min, n));
}

function hsl(h, s, l) {
  return `${((h % 360) + 360) % 360} ${clamp(s, 0, 100).toFixed(0)}% ${clamp(l, 0, 100).toFixed(0)}%`;
}

function buildTheme({ key, hue, sat, radius }) {
  const bgSat = clamp(sat * 0.12, 4, 14);
  const accentSat = clamp(sat, 20, 55);
  const darkTextOnPrimary = DARK_TEXT_ON_PRIMARY.has(key);

  const light = {
    background: hsl(hue, bgSat, 98),
    foreground: hsl(hue, bgSat + 4, 12),
    card: hsl(hue, bgSat, 100),
    "card-foreground": hsl(hue, bgSat + 4, 12),
    popover: hsl(hue, bgSat, 100),
    "popover-foreground": hsl(hue, bgSat + 4, 12),
    primary: hsl(hue, sat, 46),
    "primary-foreground": darkTextOnPrimary ? hsl(hue, 40, 12) : hsl(0, 0, 100),
    secondary: hsl(hue, bgSat, 92),
    "secondary-foreground": hsl(hue, bgSat + 4, 20),
    muted: hsl(hue, bgSat, 94),
    "muted-foreground": hsl(hue, bgSat, 40),
    accent: hsl(hue, accentSat, 90),
    "accent-foreground": hsl(hue, bgSat + 4, 15),
    destructive: hsl(0, 84, 60),
    "destructive-foreground": hsl(0, 0, 100),
    border: hsl(hue, bgSat, 88),
    input: hsl(hue, bgSat, 88),
    ring: hsl(hue, sat, 46),
  };

  const dark = {
    background: hsl(hue, bgSat + 4, 9),
    foreground: hsl(hue, bgSat, 96),
    card: hsl(hue, bgSat + 4, 12),
    "card-foreground": hsl(hue, bgSat, 96),
    popover: hsl(hue, bgSat + 4, 12),
    "popover-foreground": hsl(hue, bgSat, 96),
    primary: hsl(hue, sat, 60),
    "primary-foreground": darkTextOnPrimary ? hsl(hue, 40, 10) : hsl(hue, 30, 12),
    secondary: hsl(hue, bgSat + 4, 16),
    "secondary-foreground": hsl(hue, bgSat, 90),
    muted: hsl(hue, bgSat + 4, 18),
    "muted-foreground": hsl(hue, bgSat, 65),
    accent: hsl(hue, clamp(accentSat, 20, 50), 22),
    "accent-foreground": hsl(hue, bgSat, 92),
    destructive: hsl(0, 70, 50),
    "destructive-foreground": hsl(0, 0, 100),
    border: hsl(hue, bgSat + 4, 20),
    input: hsl(hue, bgSat + 4, 20),
    ring: hsl(hue, sat, 60),
  };

  const toBlock = (vars) =>
    Object.entries(vars)
      .map(([k, v]) => `  --${k}: ${v};`)
      .join("\n");

  return `[data-theme="${key}"] {\n  --radius: ${radius}rem;\n${toBlock(light)}\n}\n\n[data-theme="${key}"][data-mode="dark"] {\n${toBlock(dark)}\n}\n`;
}

const header = `/* AUTO-GENERATED by scripts/generate-themes.mjs — do not hand-edit.
   Change a theme's hue/sat/radius in that script and re-run it instead. */\n\n`;

const css = header + THEMES.map(buildTheme).join("\n");

writeFileSync(path.join(__dirname, "..", "src", "app", "themes.css"), css);
console.log(`Wrote ${THEMES.length} themes to src/app/themes.css`);
