import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section id={`s${n}`} className="scroll-mt-24">
      <h2 className="text-lg font-semibold tracking-tight">
        <span className="mr-2 text-muted-foreground">{n}.</span>
        {title}
      </h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-muted-foreground">{children}</div>
    </section>
  );
}

export const metadata = { title: "Disclaimer" };

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Disclaimer</h1>
      <p className="mt-3 text-sm text-muted-foreground">
        Last updated: {new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <Card className="mt-6 border-amber-500/30 bg-amber-500/5">
        <CardHeader>
          <CardTitle className="text-base">Read this before you rely on anything here</CardTitle>
        </CardHeader>
        <CardContent className="text-sm leading-relaxed text-muted-foreground">
          <p>
            <strong className="text-foreground">SignalsVault AI is not financial, investment, legal, or tax
            advice.</strong> It is an automated, rule-based system that analyzes public market data and publishes the
            reasoning behind each call. Nothing it produces is a recommendation, an offer, or a solicitation to buy,
            sell, or hold any currency, cryptocurrency, commodity, or other instrument. You are solely responsible for
            every trading or investment decision you make, and you should consult a licensed, qualified professional
            before making one.
          </p>
        </CardContent>
      </Card>

      <div className="mt-10 space-y-10">
        <Section n="1" title="Informational purposes only">
          <p>
            Every signal, verdict, score, chart, calendar entry, and piece of reasoning on this platform is provided
            for informational and educational purposes only. None of it is, or should be understood as, personalized
            financial advice, a recommendation, or an endorsement of any trading strategy, instrument, or timing.
          </p>
        </Section>

        <Section n="2" title="No guarantee of accuracy, completeness, or timeliness">
          <p>
            Signals are generated by a deterministic, rule-based engine reading technical indicators — an EMA stack,
            momentum, market structure, and candlestick confirmation — against historical and near-real-time price
            data. The engine is deliberately conservative (it withholds a call when evidence is thin, structure is
            unclear, volatility is abnormal, or a scheduled high-impact economic release is imminent), but a
            conservative system is still not an accurate one. It can and will be wrong, including in ways that lose
            money if acted on.
          </p>
          <p>
            Market data, candles, and economic-calendar events are sourced from third-party providers (currently
            Binance, Twelve Data, and a public economic-calendar feed). We do not control, and cannot guarantee, the
            accuracy, completeness, availability, or timeliness of any third-party data, and we are not liable for
            errors, delays, outages, or omissions in it.
          </p>
        </Section>

        <Section n="3" title="Substantial risk of loss">
          <p>
            Trading foreign exchange, cryptocurrency, commodities, and other leveraged or volatile instruments carries
            a high level of risk and may not be suitable for every investor. You could lose some or all of your
            initial investment; you should not trade or invest money you cannot afford to lose. Past performance of
            any signal, strategy, or track record shown on this platform — including any accuracy or backtesting
            statistics that may be published in the future — is not indicative of future results.
          </p>
        </Section>

        <Section n="4" title="Not a registered adviser; no fiduciary relationship">
          <p>
            SignalsVault AI and its operator are not a registered investment adviser, broker-dealer, futures
            commission merchant, or financial planner in any jurisdiction, and nothing on this platform creates an
            advisory, fiduciary, or client relationship between you and us. If you require personalized advice, engage
            a professional licensed to give it in your jurisdiction.
          </p>
        </Section>

        <Section n="5" title="Automated systems can fail">
          <p>
            The signal engine, data feeds, dashboard, and alerting (where offered) are software, and software fails:
            a provider can go down, a feed can return bad data, a bug can exist, an economic-calendar source can
            change its format without notice. We take reasonable care (data-quality gates, graceful degradation when
            a feed is unreachable, no repainting or retroactive rewriting of published signals) but make no warranty
            that the service will be uninterrupted, error-free, or available at any given time.
          </p>
        </Section>

        <Section n="6" title="“As is,” with no warranty">
          <p>
            The service is provided “as is” and “as available,” without warranties of any kind, express or implied,
            including — to the fullest extent permitted by law — any implied warranties of merchantability, fitness
            for a particular purpose, accuracy, or non-infringement.
          </p>
        </Section>

        <Section n="7" title="Limitation of liability">
          <p>
            To the maximum extent permitted by applicable law, SignalsVault AI and its operator will not be liable
            for any direct, indirect, incidental, consequential, special, exemplary, or punitive damages — including
            lost profits or trading losses — arising from your access to or use of, or inability to access or use,
            the service, or from any reliance placed on any signal, data, or content it provides, even if advised of
            the possibility of such damages.
          </p>
        </Section>

        <Section n="8" title="Your responsibility">
          <p>
            You are solely responsible for your own trading and investment decisions, for independently verifying any
            information before acting on it, for the position sizing and risk management you choose, and for
            complying with the laws and regulations that apply to you — including whether trading a given instrument
            is permitted, restricted, or requires a licensed intermediary in your country. Availability of this
            service does not mean it is authorized for use in every jurisdiction, and it is your responsibility to
            confirm that before using it.
          </p>
        </Section>

        <Section n="9" title="Eligibility">
          <p>
            You must be of legal age and otherwise legally permitted to use financial information services and trade
            the instruments discussed in your jurisdiction to use this service.
          </p>
        </Section>

        <Section n="10" title="Changes">
          <p>
            We may modify, suspend, or discontinue any part of the service, and may update this disclaimer, at any
            time and without prior notice. Continued use of the service after a change constitutes acceptance of the
            revised disclaimer. Material changes to pricing or paid tiers will be communicated separately, as
            described on the <a href="/pricing" className="underline underline-offset-4 hover:text-foreground">pricing page</a>.
          </p>
        </Section>

        <Section n="11" title="Contact">
          <p>
            Questions about this disclaimer can be sent to the contact address on the{" "}
            <a href="/about" className="underline underline-offset-4 hover:text-foreground">About page</a>.
          </p>
        </Section>
      </div>
    </div>
  );
}
